version: '3.9'

services:
  ignite:
    image: apacheignite/ignite
    restart: unless-stopped
    environment:
      - IGNITE_QUITE=false
    ports:
      ## default ports
      - 11211:11211
      - 47100:47100
      - 47500:47500
      - 49112:49112